buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "MinecraftForge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "Cleanroom"
            url = "https://maven.cleanroommc.com/"
        }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT"
    }
}

ext.configFile = file "build.properties"

apply plugin: 'forge'

version = "1.0.0"
group = "com.clearpause"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "eclipse"
}

// Nastavenie mena jaru az po aplikovani forge pluginu
project.archivesBaseName = "ClearPause-1.7.10"

sourceCompatibility = targetCompatibility = "1.8"
compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
}

dependencies {}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }
        
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
