buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://maven.minecraftforge.net" }
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url = "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.github.GTNewHorizons:ForgeGradle:FG_1.2:1.2.11'
    }
}

apply plugin: 'forge'

compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    options.encoding = 'UTF-8'
}

version = "2.0"
group = "net.kohi"
archivesBaseName = "kokot"

minecraft {
    version = "1.7.10-10.13.4.1558-1.7.10"
    runDir = "eclipse"
    mappings = "stable_12"
}

dependencies {
}

jar {
    manifest {
        attributes("TweakClass": "net.kohi.tcpnodelaymod.TcpNoDelayTweaker")
    }
}
